name: CI

on: 
  workflow_dispatch:

env:
  google_cloud_version: "1.19.0"

jobs:
  call-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: setv1
        run: |
          REGION="asia-northeast1"
          echo "region=${REGION}" >> $GITHUB_OUTPUT
          REF="${{ github.base_ref || github.ref }}"
          echo ${REF}

          if [[ "$REF" == "refs/heads/main" || "$REF" == "main" ]]; then
            ENV_NAME="prd"
            PROJECT_ID="${{ secrets.GCP_PROJECT_PRD }}"
          elif [[ "$REF" == "refs/heads/staging" || "$REF" == "staging" ]]; then
            ENV_NAME="stg"
            PROJECT_ID="${{ secrets.GCP_PROJECT_STG }}"
          elif [[ "$REF" == "refs/heads/developer" || "$REF" == "developer" ]]; then
            ENV_NAME="dev"
            PROJECT_ID="${{ secrets.GCP_PROJECT_DEV }}"
          fi

          echo "ENV = ${ENV_NAME}"
          echo "PROJECT = ${PROJECT_ID}"
          echo "EVENT = ${{ github.event_name }}"
          ls -la
          
      - uses: actions/checkout@v4
      - name: setv2
        run: |
          ls -la
          echo ${env.google_cloud_version}

      - name: setv3
        run: |
          ls -la
          
            
  
