name: CI

on: 
  workflow_dispatch:

env:
  google_cloud_version: "1.19.0"

jobs:
  call-ubuntu:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.setv1.outputs.env_name }}
      project: ${{ steps.setv1.outputs.project }}
    steps:
      - id: setv1
        run: |
          REGION="asia-northeast1"
          echo "region=${REGION}" >> $GITHUB_OUTPUT
          REF="${{ github.base_ref || github.ref }}"
          echo ${REF}

          if [[ "$REF" == "refs/heads/main" || "$REF" == "main" ]]; then
            ENV_NAME="prd"
            PROJECT_ID="${{ secrets.GCP_PROJECT_PRD }}"
          elif [[ "$REF" == "refs/heads/staging" || "$REF" == "staging" ]]; then
            ENV_NAME="stg"
            PROJECT_ID="${{ secrets.GCP_PROJECT_STG }}"
          elif [[ "$REF" == "refs/heads/developer" || "$REF" == "developer" ]]; then
            ENV_NAME="dev"
            PROJECT_ID="${{ secrets.GCP_PROJECT_DEV }}"
          fi

          echo "ENV = ${ENV_NAME}"
          echo "PROJECT = ${PROJECT_ID}"
          echo "EVENT = ${{ github.event_name }}"
          ls -la

          echo "env_name=${ENV_NAME}" >> $GITHUB_OUTPUT
          echo "project=${PROJECT_ID}" >> $GITHUB_OUTPUT
          
      - uses: actions/checkout@v4
      - name: setv2
        run: |
          ls -la
          echo ${{ env.google_cloud_version }}

      - name: setv3
        run: |
          ls -la

  inherit_call:
    needs: [call-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@v2
      - id: setv1
        run: |
          echo "${{ needs.call-ubuntu.outputs.env_name }}"
          echo "${{ needs.call-ubuntu.outputs.project }}"
          gcloud version
  
            
  
