name: CI

on: 
  workflow_dispatch:

jobs:
  call-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: |
          REGION="asia-northeast1"
          echo "region=${REGION}" >> $GITHUB_OUTPUT
          REF=""${{ github.base_ref || github.ref }}""
          echo ${REF}
          
            
  
